AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/MethodName:
  Exclude:
    - lib/timingapp/models/**

Metrics/BlockLength:
  Exclude:
    - schema.rb
